// DO NOT EDIT. Generated by protoc-gen-dart-ext/tools.
import './prefix.dart';

abstract class PrefixV1Localization {
  const PrefixV1Localization();

  String get zetta;
}

abstract class _Valuer {
  String of(PrefixV1Localization l);
}

class _NoPrefix implements _Valuer {
  const _NoPrefix();
  String of(PrefixV1Localization l) => '';
}

class _Zetta implements _Valuer {
  const _Zetta();
  String of(PrefixV1Localization l) => l.zetta;
}

const Map<PrefixV1, _Valuer> _valuers = {
  PrefixV1.noPrefix: const _NoPrefix(),
  PrefixV1.zetta: const _Zetta(),
};

String l10nOfPrefixV1(PrefixV1Localization l, PrefixV1 p) =>
    _valuers[p].of(l);
