// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/validators.proto

package grpc // import "github.com/empirefox/hybrid/grpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValidatorV9Error struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	ActualTag            string   `protobuf:"bytes,2,opt,name=actualTag,proto3" json:"actualTag,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	StructNamespace      string   `protobuf:"bytes,4,opt,name=structNamespace,proto3" json:"structNamespace,omitempty"`
	Field                string   `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`
	StructField          string   `protobuf:"bytes,6,opt,name=structField,proto3" json:"structField,omitempty"`
	Kind                 uint32   `protobuf:"varint,7,opt,name=kind,proto3" json:"kind,omitempty"`
	Type                 string   `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Param                string   `protobuf:"bytes,9,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorV9Error) Reset()         { *m = ValidatorV9Error{} }
func (m *ValidatorV9Error) String() string { return proto.CompactTextString(m) }
func (*ValidatorV9Error) ProtoMessage()    {}
func (*ValidatorV9Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_validators_117ec57350250ae8, []int{0}
}
func (m *ValidatorV9Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorV9Error.Unmarshal(m, b)
}
func (m *ValidatorV9Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorV9Error.Marshal(b, m, deterministic)
}
func (dst *ValidatorV9Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorV9Error.Merge(dst, src)
}
func (m *ValidatorV9Error) XXX_Size() int {
	return xxx_messageInfo_ValidatorV9Error.Size(m)
}
func (m *ValidatorV9Error) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorV9Error.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorV9Error proto.InternalMessageInfo

func (m *ValidatorV9Error) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ValidatorV9Error) GetActualTag() string {
	if m != nil {
		return m.ActualTag
	}
	return ""
}

func (m *ValidatorV9Error) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ValidatorV9Error) GetStructNamespace() string {
	if m != nil {
		return m.StructNamespace
	}
	return ""
}

func (m *ValidatorV9Error) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ValidatorV9Error) GetStructField() string {
	if m != nil {
		return m.StructField
	}
	return ""
}

func (m *ValidatorV9Error) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *ValidatorV9Error) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ValidatorV9Error) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func init() {
	proto.RegisterType((*ValidatorV9Error)(nil), "protos.ValidatorV9Error")
}

func init() { proto.RegisterFile("protos/validators.proto", fileDescriptor_validators_117ec57350250ae8) }

var fileDescriptor_validators_117ec57350250ae8 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0xbf, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xd5, 0x9f, 0x10, 0x23, 0x44, 0x65, 0x21, 0x61, 0x10, 0x43, 0xd4, 0xa9, 0x53, 0x3d,
	0x30, 0xb1, 0x22, 0xc1, 0xc8, 0x50, 0xa1, 0x0e, 0x6c, 0x17, 0xc7, 0x71, 0x2d, 0x92, 0xd8, 0xba,
	0x38, 0x88, 0x6c, 0xfc, 0xe9, 0xd4, 0x67, 0x11, 0x50, 0xb7, 0xf7, 0xbe, 0xef, 0xf9, 0x06, 0xb3,
	0x1b, 0x8f, 0x2e, 0xb8, 0x4e, 0x7e, 0x42, 0x6d, 0x4b, 0x08, 0x0e, 0xbb, 0x2d, 0x11, 0xbe, 0x4c,
	0xe2, 0xee, 0xd6, 0x38, 0x67, 0x6a, 0x2d, 0xa9, 0x16, 0x7d, 0x25, 0xa1, 0x1d, 0xd2, 0x64, 0xfd,
	0x3d, 0x65, 0xab, 0xfd, 0xef, 0xbb, 0xfd, 0xe3, 0x33, 0xa2, 0x43, 0xbe, 0x62, 0xb3, 0x00, 0x46,
	0x4c, 0xf2, 0xc9, 0x26, 0xdb, 0xc5, 0xc8, 0xef, 0x59, 0x06, 0x2a, 0xf4, 0x50, 0xbf, 0x1d, 0xf9,
	0x94, 0xf8, 0x1f, 0x88, 0xb6, 0x85, 0x46, 0x77, 0x1e, 0x94, 0x16, 0xb3, 0x64, 0x47, 0xc0, 0x37,
	0xec, 0xaa, 0x0b, 0xd8, 0xab, 0xf0, 0x3a, 0x6e, 0xe6, 0xb4, 0x39, 0xc5, 0xfc, 0x9a, 0x2d, 0x2a,
	0xab, 0xeb, 0x52, 0x2c, 0xc8, 0xa7, 0xc2, 0x73, 0x76, 0x91, 0x86, 0x2f, 0xe4, 0x96, 0xe4, 0xfe,
	0x23, 0xce, 0xd9, 0xfc, 0xc3, 0xb6, 0xa5, 0x38, 0x3b, 0xaa, 0xcb, 0x1d, 0xe5, 0xc8, 0xc2, 0xe0,
	0xb5, 0x38, 0xa7, 0x39, 0xe5, 0x78, 0xdf, 0x03, 0x42, 0x23, 0xb2, 0x74, 0x9f, 0xca, 0xd3, 0xfa,
	0x3d, 0x37, 0x36, 0x1c, 0xfa, 0x62, 0xab, 0x5c, 0x23, 0x75, 0xe3, 0x2d, 0xea, 0xca, 0x7d, 0xc9,
	0xc3, 0x50, 0xa0, 0x2d, 0xa5, 0x41, 0xaf, 0x8a, 0xf4, 0x93, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x3d, 0xfc, 0xfe, 0x51, 0x6b, 0x01, 0x00, 0x00,
}
