// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/authstore.proto

package authstore // import "github.com/empirefox/hybrid/pkg/authstore"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthKey struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,6,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthKey) Reset()         { *m = AuthKey{} }
func (m *AuthKey) String() string { return proto.CompactTextString(m) }
func (*AuthKey) ProtoMessage()    {}
func (*AuthKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_authstore_fb6cdda5a546f651, []int{0}
}
func (m *AuthKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthKey.Unmarshal(m, b)
}
func (m *AuthKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthKey.Marshal(b, m, deterministic)
}
func (dst *AuthKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthKey.Merge(dst, src)
}
func (m *AuthKey) XXX_Size() int {
	return xxx_messageInfo_AuthKey.Size(m)
}
func (m *AuthKey) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthKey.DiscardUnknown(m)
}

var xxx_messageInfo_AuthKey proto.InternalMessageInfo

func (m *AuthKey) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuthKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AuthKey) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AuthKey) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AuthKey) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AuthKey) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthKey)(nil), "protos.AuthKey")
}

func init() { proto.RegisterFile("protos/authstore.proto", fileDescriptor_authstore_fb6cdda5a546f651) }

var fileDescriptor_authstore_fb6cdda5a546f651 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0xcf, 0x31, 0x0a, 0x83, 0x30,
	0x14, 0xc6, 0x71, 0x34, 0xd6, 0x62, 0x28, 0xa5, 0x64, 0x28, 0x19, 0x3a, 0x48, 0x27, 0x4b, 0xc1,
	0x0c, 0x3d, 0x81, 0x5d, 0xbb, 0x65, 0xec, 0xa6, 0xe6, 0x55, 0x83, 0x48, 0x24, 0x89, 0xa0, 0xa7,
	0xe8, 0x95, 0x9b, 0x28, 0xd4, 0xed, 0xe3, 0xf7, 0x7f, 0xcb, 0xc3, 0xe7, 0x41, 0x2b, 0xab, 0x0c,
	0x2b, 0x47, 0xdb, 0x1a, 0xab, 0x34, 0xe4, 0x0b, 0x90, 0x78, 0xf5, 0xeb, 0x37, 0xc0, 0xfb, 0xc2,
	0xb5, 0x17, 0xcc, 0xe4, 0x88, 0x43, 0x29, 0x68, 0x90, 0x06, 0x59, 0xc4, 0xdd, 0x22, 0x27, 0x8c,
	0x3a, 0x98, 0x69, 0xe8, 0xe0, 0xc0, 0xfd, 0x24, 0x04, 0x47, 0xb6, 0x6c, 0x0c, 0x45, 0x29, 0xca,
	0x12, 0xbe, 0x6c, 0x6f, 0x02, 0x4c, 0x4d, 0x23, 0x77, 0xe6, 0xcc, 0x6f, 0x72, 0xc1, 0x49, 0xad,
	0xa1, 0xb4, 0x20, 0x0a, 0x4b, 0x77, 0x2e, 0x20, 0xbe, 0x81, 0xaf, 0x30, 0x0d, 0x52, 0x83, 0x71,
	0x35, 0x5e, 0xeb, 0x1f, 0x9e, 0xf7, 0xf7, 0xad, 0x91, 0xb6, 0x1d, 0xab, 0xbc, 0x56, 0x3d, 0x83,
	0xde, 0xfb, 0x47, 0x4d, 0xac, 0x9d, 0x2b, 0x2d, 0x05, 0x1b, 0xba, 0x66, 0x7b, 0xa6, 0x5a, 0xdf,
	0x78, 0xfc, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xc6, 0xb9, 0x0a, 0xe7, 0x00, 0x00, 0x00,
}
