// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/authstore.proto

package authstore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthKey struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,6,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthKey) Reset()         { *m = AuthKey{} }
func (m *AuthKey) String() string { return proto.CompactTextString(m) }
func (*AuthKey) ProtoMessage()    {}
func (*AuthKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a12697c55bbc06f, []int{0}
}

func (m *AuthKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthKey.Unmarshal(m, b)
}
func (m *AuthKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthKey.Marshal(b, m, deterministic)
}
func (m *AuthKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthKey.Merge(m, src)
}
func (m *AuthKey) XXX_Size() int {
	return xxx_messageInfo_AuthKey.Size(m)
}
func (m *AuthKey) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthKey.DiscardUnknown(m)
}

var xxx_messageInfo_AuthKey proto.InternalMessageInfo

func (m *AuthKey) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuthKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AuthKey) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AuthKey) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AuthKey) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AuthKey) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthKey)(nil), "protos.AuthKey")
}

func init() { proto.RegisterFile("protos/authstore.proto", fileDescriptor_9a12697c55bbc06f) }

var fileDescriptor_9a12697c55bbc06f = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcf, 0xb1, 0x6a, 0x85, 0x30,
	0x14, 0xc6, 0x71, 0x62, 0xac, 0xc5, 0x50, 0x4a, 0xc9, 0x50, 0x32, 0x74, 0x08, 0x9d, 0x52, 0x0a,
	0x66, 0xe8, 0x13, 0xd8, 0xb5, 0x5b, 0xc6, 0x6e, 0x6a, 0x4e, 0x4d, 0x10, 0x89, 0x24, 0x47, 0xd0,
	0xa7, 0xe8, 0x2b, 0x5f, 0xa2, 0x70, 0xdd, 0xfe, 0xfc, 0xbe, 0xe9, 0x63, 0xaf, 0x4b, 0x0c, 0x18,
	0x92, 0xee, 0x56, 0x74, 0x09, 0x43, 0x84, 0xe6, 0x00, 0x5e, 0x9d, 0xfe, 0xfe, 0x4f, 0xd8, 0x63,
	0xbb, 0xa2, 0xfb, 0x81, 0x9d, 0x3f, 0xb3, 0xc2, 0x5b, 0x41, 0x24, 0x51, 0xa5, 0x29, 0xbc, 0xe5,
	0x2f, 0x8c, 0x4e, 0xb0, 0x8b, 0x42, 0x12, 0xf5, 0x64, 0x72, 0x72, 0xce, 0x4a, 0xec, 0xc6, 0x24,
	0xa8, 0xa4, 0xaa, 0x36, 0x47, 0x67, 0xb3, 0x90, 0x06, 0x51, 0x4a, 0x92, 0x2d, 0x37, 0x7f, 0x63,
	0xf5, 0x10, 0xa1, 0x43, 0xb0, 0x2d, 0x8a, 0x07, 0x49, 0x14, 0x35, 0x17, 0xe4, 0x15, 0xb6, 0xc5,
	0x47, 0x48, 0x2d, 0x8a, 0xea, 0x5c, 0xef, 0xf0, 0xfd, 0xf9, 0xfb, 0x31, 0x7a, 0x74, 0x6b, 0xdf,
	0x0c, 0x61, 0xd6, 0x30, 0x67, 0xff, 0x0b, 0x9b, 0x76, 0x7b, 0x1f, 0xbd, 0xd5, 0xcb, 0x34, 0x5e,
	0x67, 0xfa, 0xf3, 0xc6, 0xd7, 0x2d, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xc6, 0xb9, 0x0a, 0xe7, 0x00,
	0x00, 0x00,
}
