// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigTree struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RootName             string   `protobuf:"bytes,2,opt,name=rootName,proto3" json:"rootName,omitempty"`
	RootPath             string   `protobuf:"bytes,3,opt,name=rootPath,proto3" json:"rootPath,omitempty"`
	ConfigName           string   `protobuf:"bytes,4,opt,name=configName,proto3" json:"configName,omitempty"`
	ConfigPath           string   `protobuf:"bytes,5,opt,name=configPath,proto3" json:"configPath,omitempty"`
	IpfsName             string   `protobuf:"bytes,6,opt,name=ipfsName,proto3" json:"ipfsName,omitempty"`
	IpfsPath             string   `protobuf:"bytes,7,opt,name=ipfsPath,proto3" json:"ipfsPath,omitempty"`
	StoreName            string   `protobuf:"bytes,8,opt,name=storeName,proto3" json:"storeName,omitempty"`
	StorePath            string   `protobuf:"bytes,9,opt,name=storePath,proto3" json:"storePath,omitempty"`
	FilesRootName        string   `protobuf:"bytes,10,opt,name=filesRootName,proto3" json:"filesRootName,omitempty"`
	FilesRootPath        string   `protobuf:"bytes,11,opt,name=filesRootPath,proto3" json:"filesRootPath,omitempty"`
	RulesRootName        string   `protobuf:"bytes,12,opt,name=rulesRootName,proto3" json:"rulesRootName,omitempty"`
	RulesRootPath        string   `protobuf:"bytes,13,opt,name=rulesRootPath,proto3" json:"rulesRootPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigTree) Reset()         { *m = ConfigTree{} }
func (m *ConfigTree) String() string { return proto.CompactTextString(m) }
func (*ConfigTree) ProtoMessage()    {}
func (*ConfigTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{0}
}

func (m *ConfigTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigTree.Unmarshal(m, b)
}
func (m *ConfigTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigTree.Marshal(b, m, deterministic)
}
func (m *ConfigTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigTree.Merge(m, src)
}
func (m *ConfigTree) XXX_Size() int {
	return xxx_messageInfo_ConfigTree.Size(m)
}
func (m *ConfigTree) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigTree.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigTree proto.InternalMessageInfo

func (m *ConfigTree) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConfigTree) GetRootName() string {
	if m != nil {
		return m.RootName
	}
	return ""
}

func (m *ConfigTree) GetRootPath() string {
	if m != nil {
		return m.RootPath
	}
	return ""
}

func (m *ConfigTree) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *ConfigTree) GetConfigPath() string {
	if m != nil {
		return m.ConfigPath
	}
	return ""
}

func (m *ConfigTree) GetIpfsName() string {
	if m != nil {
		return m.IpfsName
	}
	return ""
}

func (m *ConfigTree) GetIpfsPath() string {
	if m != nil {
		return m.IpfsPath
	}
	return ""
}

func (m *ConfigTree) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *ConfigTree) GetStorePath() string {
	if m != nil {
		return m.StorePath
	}
	return ""
}

func (m *ConfigTree) GetFilesRootName() string {
	if m != nil {
		return m.FilesRootName
	}
	return ""
}

func (m *ConfigTree) GetFilesRootPath() string {
	if m != nil {
		return m.FilesRootPath
	}
	return ""
}

func (m *ConfigTree) GetRulesRootName() string {
	if m != nil {
		return m.RulesRootName
	}
	return ""
}

func (m *ConfigTree) GetRulesRootPath() string {
	if m != nil {
		return m.RulesRootPath
	}
	return ""
}

type Basic struct {
	// @inject_tag: toml:",omitempty"
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty" toml:",omitempty"`
	// @inject_tag: toml:",omitempty" env:"HYBRID_DEV"
	Dev bool `protobuf:"varint,2,opt,name=dev,proto3" json:"dev,omitempty" toml:",omitempty" env:"HYBRID_DEV"`
	// @inject_tag: toml:",omitempty" env:"HYBRID_BIND validate:"omitempty,tcp_addr"
	Bind string `protobuf:"bytes,3,opt,name=bind,proto3" json:"bind,omitempty" toml:",omitempty" env:"HYBRID_BIND validate:"`
	// @inject_tag: toml:",omitempty" default:"200"
	FlushIntervalMs uint32 `protobuf:"varint,4,opt,name=flushIntervalMs,proto3" json:"flushIntervalMs,omitempty" toml:",omitempty" default:"200"`
	// @inject_tag: toml:",omitempty" validate:"lte=732"
	// Token is fallback token that will be veried by servers, both Ipfs
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty" toml:",omitempty" validate:"lte=732"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Basic) Reset()         { *m = Basic{} }
func (m *Basic) String() string { return proto.CompactTextString(m) }
func (*Basic) ProtoMessage()    {}
func (*Basic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{1}
}

func (m *Basic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Basic.Unmarshal(m, b)
}
func (m *Basic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Basic.Marshal(b, m, deterministic)
}
func (m *Basic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Basic.Merge(m, src)
}
func (m *Basic) XXX_Size() int {
	return xxx_messageInfo_Basic.Size(m)
}
func (m *Basic) XXX_DiscardUnknown() {
	xxx_messageInfo_Basic.DiscardUnknown(m)
}

var xxx_messageInfo_Basic proto.InternalMessageInfo

func (m *Basic) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Basic) GetDev() bool {
	if m != nil {
		return m.Dev
	}
	return false
}

func (m *Basic) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

func (m *Basic) GetFlushIntervalMs() uint32 {
	if m != nil {
		return m.FlushIntervalMs
	}
	return 0
}

func (m *Basic) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Log struct {
	// @inject_tag: toml:",omitempty"
	Dev bool `protobuf:"varint,1,opt,name=dev,proto3" json:"dev,omitempty" toml:",omitempty"`
	// @inject_tag: toml:",omitempty" validate:"omitempty,oneof=debug info warn error dpanic panic fatal"
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty" toml:",omitempty" validate:"omitempty,oneof=debug info warn error dpanic panic fatal"`
	// @inject_tag: toml:",omitempty"
	// Target accepts "tcp://host:port?timeout=5s", file, sentryDSN, empty or "nop".
	// Register NewTCPSink to support tcp sink. Default is stderr.
	Target               string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty" toml:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{2}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetDev() bool {
	if m != nil {
		return m.Dev
	}
	return false
}

func (m *Log) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Log) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type Ipfs struct {
	// @inject_tag: toml:",omitempty" validate:"tcp_addr" default:"127.0.127.1:1270"
	FakeApiListenAddr string `protobuf:"bytes,1,opt,name=fakeApiListenAddr,proto3" json:"fakeApiListenAddr,omitempty" toml:",omitempty" validate:"tcp_addr" default:"127.0.127.1:1270"`
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname"
	GatewayServerName string `protobuf:"bytes,2,opt,name=gatewayServerName,proto3" json:"gatewayServerName,omitempty" toml:",omitempty" validate:"omitempty,hostname"`
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname"
	ApiServerName string `protobuf:"bytes,3,opt,name=apiServerName,proto3" json:"apiServerName,omitempty" toml:",omitempty" validate:"omitempty,hostname"`
	// @inject_tag: toml:",omitempty" validate:"unique"
	Profile []string `protobuf:"bytes,4,rep,name=profile,proto3" json:"profile,omitempty" toml:",omitempty" validate:"unique"`
	// @inject_tag: toml:",omitempty"
	AutoMigrate bool `protobuf:"varint,5,opt,name=autoMigrate,proto3" json:"autoMigrate,omitempty" toml:",omitempty"`
	// @inject_tag: toml:",omitempty"
	EnableIpnsPubSub bool `protobuf:"varint,6,opt,name=enableIpnsPubSub,proto3" json:"enableIpnsPubSub,omitempty" toml:",omitempty"`
	// @inject_tag: toml:",omitempty"
	EnablePubSub bool `protobuf:"varint,7,opt,name=enablePubSub,proto3" json:"enablePubSub,omitempty" toml:",omitempty"`
	// @inject_tag: toml:",omitempty"
	EnableMultiplex bool `protobuf:"varint,8,opt,name=enableMultiplex,proto3" json:"enableMultiplex,omitempty" toml:",omitempty"`
	// @inject_tag: toml:",omitempty" validate:"lte=732"
	Token                string   `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty" toml:",omitempty" validate:"lte=732"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ipfs) Reset()         { *m = Ipfs{} }
func (m *Ipfs) String() string { return proto.CompactTextString(m) }
func (*Ipfs) ProtoMessage()    {}
func (*Ipfs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{3}
}

func (m *Ipfs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipfs.Unmarshal(m, b)
}
func (m *Ipfs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipfs.Marshal(b, m, deterministic)
}
func (m *Ipfs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipfs.Merge(m, src)
}
func (m *Ipfs) XXX_Size() int {
	return xxx_messageInfo_Ipfs.Size(m)
}
func (m *Ipfs) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipfs.DiscardUnknown(m)
}

var xxx_messageInfo_Ipfs proto.InternalMessageInfo

func (m *Ipfs) GetFakeApiListenAddr() string {
	if m != nil {
		return m.FakeApiListenAddr
	}
	return ""
}

func (m *Ipfs) GetGatewayServerName() string {
	if m != nil {
		return m.GatewayServerName
	}
	return ""
}

func (m *Ipfs) GetApiServerName() string {
	if m != nil {
		return m.ApiServerName
	}
	return ""
}

func (m *Ipfs) GetProfile() []string {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Ipfs) GetAutoMigrate() bool {
	if m != nil {
		return m.AutoMigrate
	}
	return false
}

func (m *Ipfs) GetEnableIpnsPubSub() bool {
	if m != nil {
		return m.EnableIpnsPubSub
	}
	return false
}

func (m *Ipfs) GetEnablePubSub() bool {
	if m != nil {
		return m.EnablePubSub
	}
	return false
}

func (m *Ipfs) GetEnableMultiplex() bool {
	if m != nil {
		return m.EnableMultiplex
	}
	return false
}

func (m *Ipfs) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IpfsServer struct {
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:",omitempty" validate:"omitempty,hostname"`
	// @inject_tag: toml:",omitempty" validate:"required"
	Peer string `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty" toml:",omitempty" validate:"required"`
	// @inject_tag: toml:",omitempty" validate:"lte=732"
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty" toml:",omitempty" validate:"lte=732"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpfsServer) Reset()         { *m = IpfsServer{} }
func (m *IpfsServer) String() string { return proto.CompactTextString(m) }
func (*IpfsServer) ProtoMessage()    {}
func (*IpfsServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{4}
}

func (m *IpfsServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpfsServer.Unmarshal(m, b)
}
func (m *IpfsServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpfsServer.Marshal(b, m, deterministic)
}
func (m *IpfsServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpfsServer.Merge(m, src)
}
func (m *IpfsServer) XXX_Size() int {
	return xxx_messageInfo_IpfsServer.Size(m)
}
func (m *IpfsServer) XXX_DiscardUnknown() {
	xxx_messageInfo_IpfsServer.DiscardUnknown(m)
}

var xxx_messageInfo_IpfsServer proto.InternalMessageInfo

func (m *IpfsServer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IpfsServer) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *IpfsServer) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type FileServer struct {
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:",omitempty" validate:"omitempty,hostname"`
	// @inject_tag: toml:",omitempty" validate:"hostname"
	Zip string `protobuf:"bytes,2,opt,name=zip,proto3" json:"zip,omitempty" toml:",omitempty" validate:"hostname"`
	// @inject_tag: toml:",omitempty"
	Redirect map[string]string `protobuf:"bytes,3,rep,name=redirect,proto3" json:"redirect,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" toml:",omitempty"`
	// @inject_tag: toml:",omitempty"
	Dev                  bool     `protobuf:"varint,4,opt,name=dev,proto3" json:"dev,omitempty" toml:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileServer) Reset()         { *m = FileServer{} }
func (m *FileServer) String() string { return proto.CompactTextString(m) }
func (*FileServer) ProtoMessage()    {}
func (*FileServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{5}
}

func (m *FileServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileServer.Unmarshal(m, b)
}
func (m *FileServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileServer.Marshal(b, m, deterministic)
}
func (m *FileServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileServer.Merge(m, src)
}
func (m *FileServer) XXX_Size() int {
	return xxx_messageInfo_FileServer.Size(m)
}
func (m *FileServer) XXX_DiscardUnknown() {
	xxx_messageInfo_FileServer.DiscardUnknown(m)
}

var xxx_messageInfo_FileServer proto.InternalMessageInfo

func (m *FileServer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileServer) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *FileServer) GetRedirect() map[string]string {
	if m != nil {
		return m.Redirect
	}
	return nil
}

func (m *FileServer) GetDev() bool {
	if m != nil {
		return m.Dev
	}
	return false
}

type HttpProxyServer struct {
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:",omitempty" validate:"omitempty,hostname"`
	// @inject_tag: toml:",omitempty" validate:"tcp_addr"
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty" toml:",omitempty" validate:"tcp_addr"`
	// @inject_tag: toml:",omitempty"
	KeepAlive            bool     `protobuf:"varint,3,opt,name=keepAlive,proto3" json:"keepAlive,omitempty" toml:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpProxyServer) Reset()         { *m = HttpProxyServer{} }
func (m *HttpProxyServer) String() string { return proto.CompactTextString(m) }
func (*HttpProxyServer) ProtoMessage()    {}
func (*HttpProxyServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{6}
}

func (m *HttpProxyServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpProxyServer.Unmarshal(m, b)
}
func (m *HttpProxyServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpProxyServer.Marshal(b, m, deterministic)
}
func (m *HttpProxyServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpProxyServer.Merge(m, src)
}
func (m *HttpProxyServer) XXX_Size() int {
	return xxx_messageInfo_HttpProxyServer.Size(m)
}
func (m *HttpProxyServer) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpProxyServer.DiscardUnknown(m)
}

var xxx_messageInfo_HttpProxyServer proto.InternalMessageInfo

func (m *HttpProxyServer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HttpProxyServer) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HttpProxyServer) GetKeepAlive() bool {
	if m != nil {
		return m.KeepAlive
	}
	return false
}

type AdpRouter struct {
	// @inject_tag: toml:",omitempty" validate:"hostname"
	// *.b64 is base64 encoded.
	// *.ipfs is fetched from ipfs network.
	// ipfs file is of toml format:
	//   [[Ipfs]]
	//   Path = "Qmxxx..xA"
	//   Base64 = true
	//
	//   [[Ipfs]]
	//   Path = "Qmxxx..xB"
	RulesDirName string `protobuf:"bytes,1,opt,name=rulesDirName,proto3" json:"rulesDirName,omitempty" toml:",omitempty" validate:"hostname"`
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname"
	Blocked string `protobuf:"bytes,2,opt,name=blocked,proto3" json:"blocked,omitempty" toml:",omitempty" validate:"omitempty,hostname"`
	// @inject_tag: toml:",omitempty" omitempty,hostname,nefield=Blocked"
	Unblocked string `protobuf:"bytes,3,opt,name=unblocked,proto3" json:"unblocked,omitempty" toml:",omitempty"`
	// @inject_tag: toml:",omitempty"
	EtcHostsIpAsBlocked bool `protobuf:"varint,4,opt,name=etcHostsIpAsBlocked,proto3" json:"etcHostsIpAsBlocked,omitempty" toml:",omitempty"`
	// @inject_tag: toml:",omitempty"
	Dev                  bool     `protobuf:"varint,5,opt,name=dev,proto3" json:"dev,omitempty" toml:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdpRouter) Reset()         { *m = AdpRouter{} }
func (m *AdpRouter) String() string { return proto.CompactTextString(m) }
func (*AdpRouter) ProtoMessage()    {}
func (*AdpRouter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{7}
}

func (m *AdpRouter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdpRouter.Unmarshal(m, b)
}
func (m *AdpRouter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdpRouter.Marshal(b, m, deterministic)
}
func (m *AdpRouter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdpRouter.Merge(m, src)
}
func (m *AdpRouter) XXX_Size() int {
	return xxx_messageInfo_AdpRouter.Size(m)
}
func (m *AdpRouter) XXX_DiscardUnknown() {
	xxx_messageInfo_AdpRouter.DiscardUnknown(m)
}

var xxx_messageInfo_AdpRouter proto.InternalMessageInfo

func (m *AdpRouter) GetRulesDirName() string {
	if m != nil {
		return m.RulesDirName
	}
	return ""
}

func (m *AdpRouter) GetBlocked() string {
	if m != nil {
		return m.Blocked
	}
	return ""
}

func (m *AdpRouter) GetUnblocked() string {
	if m != nil {
		return m.Unblocked
	}
	return ""
}

func (m *AdpRouter) GetEtcHostsIpAsBlocked() bool {
	if m != nil {
		return m.EtcHostsIpAsBlocked
	}
	return false
}

func (m *AdpRouter) GetDev() bool {
	if m != nil {
		return m.Dev
	}
	return false
}

type IPNetRouter struct {
	// @inject_tag: toml:",omitempty" validate:"dive,ip"
	Ip []string `protobuf:"bytes,1,rep,name=ip,proto3" json:"ip,omitempty" toml:",omitempty" validate:"dive,ip"`
	// @inject_tag: toml:",omitempty" validate:"dive,cidr"
	Net []string `protobuf:"bytes,2,rep,name=net,proto3" json:"net,omitempty" toml:",omitempty" validate:"dive,cidr"`
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname"
	Matched string `protobuf:"bytes,3,opt,name=matched,proto3" json:"matched,omitempty" toml:",omitempty" validate:"omitempty,hostname"`
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname,nefield=Matched"
	Unmatched string `protobuf:"bytes,4,opt,name=unmatched,proto3" json:"unmatched,omitempty" toml:",omitempty" validate:"omitempty,hostname,nefield=Matched"`
	// @inject_tag: toml:",omitempty" validate:"omitempty,hostname"
	FileTest             string   `protobuf:"bytes,5,opt,name=fileTest,proto3" json:"fileTest,omitempty" toml:",omitempty" validate:"omitempty,hostname"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPNetRouter) Reset()         { *m = IPNetRouter{} }
func (m *IPNetRouter) String() string { return proto.CompactTextString(m) }
func (*IPNetRouter) ProtoMessage()    {}
func (*IPNetRouter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{8}
}

func (m *IPNetRouter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPNetRouter.Unmarshal(m, b)
}
func (m *IPNetRouter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPNetRouter.Marshal(b, m, deterministic)
}
func (m *IPNetRouter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPNetRouter.Merge(m, src)
}
func (m *IPNetRouter) XXX_Size() int {
	return xxx_messageInfo_IPNetRouter.Size(m)
}
func (m *IPNetRouter) XXX_DiscardUnknown() {
	xxx_messageInfo_IPNetRouter.DiscardUnknown(m)
}

var xxx_messageInfo_IPNetRouter proto.InternalMessageInfo

func (m *IPNetRouter) GetIp() []string {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *IPNetRouter) GetNet() []string {
	if m != nil {
		return m.Net
	}
	return nil
}

func (m *IPNetRouter) GetMatched() string {
	if m != nil {
		return m.Matched
	}
	return ""
}

func (m *IPNetRouter) GetUnmatched() string {
	if m != nil {
		return m.Unmatched
	}
	return ""
}

func (m *IPNetRouter) GetFileTest() string {
	if m != nil {
		return m.FileTest
	}
	return ""
}

type RouterItem struct {
	// @inject_tag: validate:"hostname"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"hostname"`
	// Types that are valid to be assigned to Router:
	//	*RouterItem_Adp
	//	*RouterItem_Ipnet
	Router               isRouterItem_Router `protobuf_oneof:"router"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RouterItem) Reset()         { *m = RouterItem{} }
func (m *RouterItem) String() string { return proto.CompactTextString(m) }
func (*RouterItem) ProtoMessage()    {}
func (*RouterItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{9}
}

func (m *RouterItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouterItem.Unmarshal(m, b)
}
func (m *RouterItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouterItem.Marshal(b, m, deterministic)
}
func (m *RouterItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouterItem.Merge(m, src)
}
func (m *RouterItem) XXX_Size() int {
	return xxx_messageInfo_RouterItem.Size(m)
}
func (m *RouterItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RouterItem.DiscardUnknown(m)
}

var xxx_messageInfo_RouterItem proto.InternalMessageInfo

func (m *RouterItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isRouterItem_Router interface {
	isRouterItem_Router()
}

type RouterItem_Adp struct {
	Adp *AdpRouter `protobuf:"bytes,2,opt,name=adp,proto3,oneof"`
}

type RouterItem_Ipnet struct {
	Ipnet *IPNetRouter `protobuf:"bytes,3,opt,name=ipnet,proto3,oneof"`
}

func (*RouterItem_Adp) isRouterItem_Router() {}

func (*RouterItem_Ipnet) isRouterItem_Router() {}

func (m *RouterItem) GetRouter() isRouterItem_Router {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *RouterItem) GetAdp() *AdpRouter {
	if x, ok := m.GetRouter().(*RouterItem_Adp); ok {
		return x.Adp
	}
	return nil
}

func (m *RouterItem) GetIpnet() *IPNetRouter {
	if x, ok := m.GetRouter().(*RouterItem_Ipnet); ok {
		return x.Ipnet
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RouterItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RouterItem_Adp)(nil),
		(*RouterItem_Ipnet)(nil),
	}
}

// reserved names: DIRECT over with hybrid
// env:
// HYBRID_ROOT_PATH=$HOME/.hybrid
// HYBRID_DEV=false
// HYBRID_BIND=:7777
// HYBRID_FILE_SERVERS_DISABLED=a,b,c
// HYBRID_ROUTER_DISABLED=a,b,c
type Config struct {
	// @inject_tag: default:"{}"
	Basic *Basic `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty" default:"{}"`
	// @inject_tag: default:"{}"
	Log *Log `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty" default:"{}"`
	// @inject_tag: default:"{}"
	Ipfs                 *Ipfs              `protobuf:"bytes,3,opt,name=ipfs,proto3" json:"ipfs,omitempty" default:"{}"`
	IpfsServers          []*IpfsServer      `protobuf:"bytes,4,rep,name=ipfsServers,proto3" json:"ipfsServers,omitempty"`
	FileServers          []*FileServer      `protobuf:"bytes,5,rep,name=fileServers,proto3" json:"fileServers,omitempty"`
	HttpProxyServers     []*HttpProxyServer `protobuf:"bytes,6,rep,name=httpProxyServers,proto3" json:"httpProxyServers,omitempty"`
	Routers              []*RouterItem      `protobuf:"bytes,7,rep,name=routers,proto3" json:"routers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_d554bc413a6b2d8c, []int{10}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetBasic() *Basic {
	if m != nil {
		return m.Basic
	}
	return nil
}

func (m *Config) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *Config) GetIpfs() *Ipfs {
	if m != nil {
		return m.Ipfs
	}
	return nil
}

func (m *Config) GetIpfsServers() []*IpfsServer {
	if m != nil {
		return m.IpfsServers
	}
	return nil
}

func (m *Config) GetFileServers() []*FileServer {
	if m != nil {
		return m.FileServers
	}
	return nil
}

func (m *Config) GetHttpProxyServers() []*HttpProxyServer {
	if m != nil {
		return m.HttpProxyServers
	}
	return nil
}

func (m *Config) GetRouters() []*RouterItem {
	if m != nil {
		return m.Routers
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigTree)(nil), "protos.ConfigTree")
	proto.RegisterType((*Basic)(nil), "protos.Basic")
	proto.RegisterType((*Log)(nil), "protos.Log")
	proto.RegisterType((*Ipfs)(nil), "protos.Ipfs")
	proto.RegisterType((*IpfsServer)(nil), "protos.IpfsServer")
	proto.RegisterType((*FileServer)(nil), "protos.FileServer")
	proto.RegisterMapType((map[string]string)(nil), "protos.FileServer.RedirectEntry")
	proto.RegisterType((*HttpProxyServer)(nil), "protos.HttpProxyServer")
	proto.RegisterType((*AdpRouter)(nil), "protos.AdpRouter")
	proto.RegisterType((*IPNetRouter)(nil), "protos.IPNetRouter")
	proto.RegisterType((*RouterItem)(nil), "protos.RouterItem")
	proto.RegisterType((*Config)(nil), "protos.Config")
}

func init() { proto.RegisterFile("protos/config.proto", fileDescriptor_d554bc413a6b2d8c) }

var fileDescriptor_d554bc413a6b2d8c = []byte{
	// 934 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xcf, 0x6e, 0x23, 0xc5,
	0x13, 0x5e, 0x7b, 0x6c, 0x67, 0x5c, 0x13, 0xff, 0x36, 0xdb, 0x59, 0xfd, 0xb0, 0x22, 0x40, 0xd6,
	0xb0, 0x48, 0x11, 0xac, 0x12, 0x64, 0x38, 0x20, 0xe0, 0xe2, 0x2c, 0x8b, 0x62, 0x94, 0xac, 0xa2,
	0xde, 0x95, 0x90, 0xb8, 0x8d, 0xed, 0xb2, 0xdd, 0xf2, 0x78, 0x7a, 0xd4, 0xdd, 0x63, 0x62, 0x0e,
	0x5c, 0x38, 0xf0, 0x2e, 0xf0, 0x10, 0x3c, 0x01, 0x37, 0x1e, 0x08, 0xf5, 0xbf, 0xf9, 0xe3, 0xac,
	0x72, 0xeb, 0xfa, 0xbe, 0xaf, 0xaa, 0xab, 0xab, 0xaa, 0x7b, 0x06, 0x4e, 0x73, 0xc1, 0x15, 0x97,
	0x97, 0x73, 0x9e, 0x2d, 0xd9, 0xea, 0xc2, 0x58, 0xa4, 0x67, 0xc1, 0xf8, 0xcf, 0x00, 0xe0, 0x95,
	0x21, 0xde, 0x09, 0x44, 0x32, 0x84, 0xa3, 0x1d, 0x0a, 0xc9, 0x78, 0x36, 0x6c, 0x8d, 0x5a, 0xe7,
	0x7d, 0xea, 0x4d, 0x72, 0x06, 0xa1, 0xe0, 0x5c, 0xbd, 0x49, 0xb6, 0x38, 0x6c, 0x1b, 0xaa, 0xb4,
	0x3d, 0x77, 0x97, 0xa8, 0xf5, 0x30, 0xa8, 0x38, 0x6d, 0x93, 0x8f, 0x01, 0xec, 0xc6, 0xc6, 0xb3,
	0x63, 0xd8, 0x1a, 0x52, 0xf1, 0xc6, 0xbb, 0x5b, 0xe7, 0x8d, 0xff, 0x19, 0x84, 0x2c, 0x5f, 0x4a,
	0xe3, 0xdd, 0xb3, 0xb1, 0xbd, 0xed, 0x39, 0xe3, 0x79, 0x54, 0x71, 0xc6, 0xef, 0x43, 0xe8, 0x4b,
	0xc5, 0x05, 0x1a, 0xc7, 0xd0, 0x90, 0x15, 0x50, 0xb2, 0xc6, 0xb5, 0x5f, 0x63, 0x8d, 0xef, 0x0b,
	0x18, 0x2c, 0x59, 0x8a, 0x92, 0xfa, 0x03, 0x83, 0x51, 0x34, 0xc1, 0x86, 0xca, 0xc4, 0x89, 0x0e,
	0x54, 0x3e, 0x96, 0x28, 0xea, 0xb1, 0x8e, 0xad, 0xaa, 0x01, 0x36, 0x54, 0x26, 0xd6, 0xe0, 0x40,
	0xa5, 0xc1, 0xf8, 0x8f, 0x16, 0x74, 0xaf, 0x12, 0xc9, 0xe6, 0x8f, 0xf4, 0xe9, 0x04, 0x82, 0x05,
	0xee, 0x4c, 0x8b, 0x42, 0xaa, 0x97, 0x84, 0x40, 0x67, 0xc6, 0xb2, 0x85, 0xeb, 0x8c, 0x59, 0x93,
	0x73, 0x78, 0xba, 0x4c, 0x0b, 0xb9, 0x9e, 0x66, 0x0a, 0xc5, 0x2e, 0x49, 0x6f, 0xa5, 0x69, 0xcd,
	0x80, 0x1e, 0xc2, 0xe4, 0x39, 0x74, 0x15, 0xdf, 0x60, 0xe6, 0x5a, 0x63, 0x8d, 0xf8, 0x35, 0x04,
	0x37, 0x7c, 0xe5, 0x37, 0x6b, 0x55, 0x9b, 0x3d, 0x87, 0x6e, 0x8a, 0x3b, 0x4c, 0xdd, 0x8c, 0x58,
	0x83, 0xfc, 0x1f, 0x7a, 0x2a, 0x11, 0x2b, 0x54, 0x2e, 0x09, 0x67, 0xc5, 0xff, 0xb6, 0xa1, 0x33,
	0xcd, 0x97, 0x92, 0xbc, 0x84, 0x67, 0xcb, 0x64, 0x83, 0x93, 0x9c, 0xdd, 0x30, 0xa9, 0x30, 0x9b,
	0x2c, 0x16, 0xc2, 0x9d, 0xec, 0x21, 0xa1, 0xd5, 0xab, 0x44, 0xe1, 0x2f, 0xc9, 0xfe, 0x2d, 0x8a,
	0x1d, 0x8a, 0xda, 0x50, 0x3e, 0x24, 0x74, 0x6d, 0x93, 0x9c, 0xd5, 0x94, 0x36, 0x87, 0x26, 0xa8,
	0x2b, 0x9a, 0x0b, 0xae, 0x7b, 0x37, 0xec, 0x8c, 0x02, 0x5d, 0x51, 0x67, 0x92, 0x11, 0x44, 0x49,
	0xa1, 0xf8, 0x2d, 0x5b, 0x89, 0x44, 0xa1, 0xa9, 0x43, 0x48, 0xeb, 0x10, 0xf9, 0x0c, 0x4e, 0x30,
	0x4b, 0x66, 0x29, 0x4e, 0xf3, 0x4c, 0xde, 0x15, 0xb3, 0xb7, 0xc5, 0xcc, 0xcc, 0x6a, 0x48, 0x1f,
	0xe0, 0x24, 0x86, 0x63, 0x8b, 0x39, 0xdd, 0x91, 0xd1, 0x35, 0x30, 0xdd, 0x1d, 0x6b, 0xdf, 0x16,
	0xa9, 0x62, 0x79, 0x8a, 0xf7, 0x66, 0x82, 0x43, 0x7a, 0x08, 0x57, 0xdd, 0xe9, 0xd7, 0xbb, 0xf3,
	0x23, 0x80, 0xae, 0xaa, 0x3d, 0x9d, 0xee, 0x7f, 0xa6, 0x8f, 0x6d, 0xcb, 0x69, 0xd6, 0x1a, 0xcb,
	0x11, 0x85, 0x2b, 0x9a, 0x59, 0x57, 0xb1, 0x82, 0x7a, 0xac, 0xbf, 0x5b, 0x00, 0x3f, 0xb0, 0x14,
	0x1f, 0x09, 0x76, 0x02, 0xc1, 0xaf, 0x2c, 0x77, 0xb1, 0xf4, 0x92, 0x7c, 0x07, 0xa1, 0xc0, 0x05,
	0x13, 0x38, 0xd7, 0x1d, 0x0f, 0xce, 0xa3, 0xf1, 0xc8, 0xbe, 0x3b, 0xf2, 0xa2, 0x8a, 0x75, 0x41,
	0x9d, 0xe4, 0x75, 0xa6, 0xc4, 0x9e, 0x96, 0x1e, 0x7e, 0xaa, 0x3a, 0xe5, 0x54, 0x9d, 0x7d, 0x0b,
	0x83, 0x86, 0x58, 0x4b, 0x36, 0xb8, 0x77, 0x59, 0xe8, 0xa5, 0xce, 0x7e, 0x97, 0xa4, 0x85, 0x9f,
	0x03, 0x6b, 0x7c, 0xd3, 0xfe, 0xba, 0x15, 0xff, 0x04, 0x4f, 0xaf, 0x95, 0xca, 0xef, 0x04, 0xbf,
	0xdf, 0x3f, 0x5e, 0x92, 0x35, 0x97, 0xca, 0x97, 0x44, 0xaf, 0xf5, 0x33, 0xb1, 0x41, 0xcc, 0x27,
	0x29, 0xdb, 0xd9, 0xb1, 0x09, 0x69, 0x05, 0xc4, 0x7f, 0xb5, 0xa0, 0x3f, 0x59, 0xe4, 0x94, 0x17,
	0x0a, 0x85, 0x6e, 0xac, 0xb9, 0xad, 0xdf, 0x33, 0x3b, 0x65, 0x36, 0x76, 0x03, 0xd3, 0x43, 0x36,
	0x4b, 0xf9, 0x7c, 0x83, 0x0b, 0xb7, 0x8d, 0x37, 0xf5, 0x4e, 0x45, 0xe6, 0x39, 0xdb, 0x80, 0x0a,
	0x20, 0x5f, 0xc0, 0x29, 0xaa, 0xf9, 0x35, 0x97, 0x4a, 0x4e, 0xf3, 0x89, 0xbc, 0x72, 0x3a, 0x5b,
	0xa1, 0xf7, 0x51, 0xbe, 0x86, 0xdd, 0xb2, 0x86, 0xf1, 0xef, 0x2d, 0x88, 0xa6, 0x77, 0x6f, 0x50,
	0xb9, 0x7c, 0xff, 0x07, 0x6d, 0x96, 0x0f, 0x5b, 0x66, 0xd6, 0xdb, 0x2c, 0xd7, 0x1e, 0x19, 0xea,
	0xe3, 0x6b, 0x40, 0x2f, 0x75, 0xb6, 0xdb, 0x44, 0xcd, 0xd7, 0x65, 0x46, 0xde, 0xb4, 0xd9, 0x7a,
	0xae, 0xe3, 0xb3, 0xf5, 0xec, 0x19, 0x84, 0xfa, 0xe2, 0xbc, 0x43, 0xa9, 0xdc, 0xab, 0x51, 0xda,
	0xf1, 0x6f, 0x00, 0x76, 0xff, 0xa9, 0xc2, 0xed, 0x7b, 0xfb, 0xf0, 0x29, 0x04, 0xc9, 0xc2, 0x4e,
	0x53, 0x34, 0x7e, 0xe6, 0xc7, 0xa6, 0xac, 0xf3, 0xf5, 0x13, 0xaa, 0x79, 0xf2, 0x39, 0x74, 0x59,
	0x9e, 0xb9, 0x17, 0x25, 0x1a, 0x9f, 0x7a, 0x61, 0xed, 0x88, 0xd7, 0x4f, 0xa8, 0xd5, 0x5c, 0x85,
	0xd0, 0x13, 0x06, 0x8a, 0xff, 0x69, 0x43, 0xcf, 0x7e, 0xef, 0xc8, 0x27, 0xd0, 0x9d, 0xe9, 0xc7,
	0xd4, 0xec, 0x1e, 0x8d, 0x07, 0x3e, 0x82, 0x79, 0x61, 0xa9, 0xe5, 0xc8, 0x47, 0x10, 0xa4, 0x7c,
	0xe5, 0xb2, 0x89, 0xbc, 0xe4, 0x86, 0xaf, 0xa8, 0xc6, 0xc9, 0x08, 0x3a, 0xfa, 0x8b, 0xe3, 0x92,
	0x38, 0x2e, 0x93, 0xc8, 0x97, 0x92, 0x1a, 0x86, 0x7c, 0x05, 0x11, 0x2b, 0xef, 0xa2, 0x34, 0x6f,
	0x4b, 0x34, 0x26, 0x75, 0xa1, 0xa5, 0x68, 0x5d, 0xa6, 0xbd, 0x96, 0xe5, 0x45, 0x91, 0xc3, 0x6e,
	0xd3, 0xab, 0xba, 0x43, 0xb4, 0x2e, 0x23, 0xaf, 0xe0, 0x64, 0xdd, 0x9c, 0x74, 0x39, 0xec, 0x19,
	0xd7, 0x0f, 0xbc, 0xeb, 0xc1, 0x4d, 0xa0, 0x0f, 0x1c, 0xc8, 0x4b, 0x38, 0xb2, 0xb5, 0x92, 0xc3,
	0xa3, 0xe6, 0xb6, 0x55, 0xe3, 0xa8, 0x97, 0x5c, 0xbd, 0xf8, 0x39, 0x5e, 0x31, 0xb5, 0x2e, 0x66,
	0x17, 0x73, 0xbe, 0xbd, 0xc4, 0x6d, 0xce, 0x04, 0x2e, 0xf9, 0xfd, 0xe5, 0x7a, 0x3f, 0x13, 0x6c,
	0xe1, 0xfe, 0x39, 0x66, 0xf6, 0x6f, 0xe3, 0xcb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x34,
	0xef, 0xa2, 0x8b, 0x08, 0x00, 0x00,
}
